# plan-apply-on-merge.yaml
name: Plan /Apply On Merge

on:
  push:
    branches: [main]
  pull_request:
    types: [closed]

jobs:
  inform_about_apply:
    name: Inform About /Apply
    runs-on: ubuntu-latest

    steps:
      - name: Inform on PR that Apply is Running
        uses: mshick/add-pr-comment@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'github-actions[bot]'
          message: |
            ***Running terraform apply***
            Results will display here momentarily...

  plan_and_apply:
    name: Plan and Apply
    environment:
      name: production
      url: https://github.com
    env:
      TF_VAR_admin_email: ${{ secrets.ADMIN_EMAIL }}
      TF_VAR_organization_name: ${{ secrets.ORGANIZATION_NAME }}
      TF_VAR_create_organization: true
      TF_VAR_github_pat_token: ${{ secrets.PAT }}
      TF_VAR_terraform_api_token: ${{ secrets.TF_API_TOKEN }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        path:
          - terraform

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Write remote.tf file
        uses: DamianReeves/write-file-action@v1.0
        with:
          path: ${{ matrix.path }}
          contents: |
            terraform {
              cloud {
                organization = "${{ secrets.ORGANIZATION_NAME }}"

                workspaces {
                  name = "${{ secrets.ORGANIZATION_NAME }}"
                }
              }
            }

      - name: Write private.tfvars file
        uses: DamianReeves/write-file-action@v1.0
        with:
          path: ${{ matrix.path }}
          contents: |
            workspace = {
              sophos-xdr = {
                add_vcs_repo                  = true
                agent_pool_id                 = ""
                allow_destroy_plan            = false
                auto_apply                    = true
                create_variable_set           = true
                execution_mode                = "remote"
                file_triggers_enabled         = false
                global                        = true
                global_remote_state           = true
                name                          = "${{ secrets.ORGANIZATION_NAME }}"
                oauth_token_id                = ""
                organization                  = ""
                queue_all_runs                = false
                remote_state_consumer_ids     = ""
                speculative_enabled           = false
                structured_run_output_enabled = true
                ssh_key_id                    = ""
                terraform_version             = ""
                tfe_token                     = ""
                trigger_prefixes              = [""]
                tags                          = ["${{ secrets.ORGANIZATION_NAME }}"]
                vcs_branch                    = "main"
                vcs_repository                = "${{ github.repository }}"
                workspace_description         = "Backend remote state for ${{ secrets.ORGANIZATION_NAME }}"
                working_directory             = "./terraform"
                workspace_variable            = false
              }
            }

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Initialize Terraform
        run: |
          cd ${{ matrix.path }}
          terraform init -input=false

      - name: Plan Terraform
        id: plan
        continue-on-error: true
        run: |
          cd ${{ matrix.path }}
          terraform plan -input=false -no-color -out=tfplan \
          && terraform show -no-color tfplan
        env:
          TF_VAR_admin_email: ${{ secrets.ADMIN_EMAIL }}
          TF_VAR_organization_name: ${{ secrets.ORGANIZATION_NAME }}
          TF_VAR_create_organization: true
          TF_VAR_github_pat_token: ${{ secrets.PAT }}
          TF_VAR_terraform_api_token: ${{ secrets.TF_API_TOKEN }}

      - name: Reformat Plan
        if: steps.plan.outcome == 'success'
        run: |
          echo '${{ steps.plan.outputs.stdout || steps.plan.outputs.stderr }}' \
          | sed -E 's/^([[:space:]]+)([-+])/\2\1/g' > plan.txt

      - name: Put Plan in Env Var
        if: steps.plan.outcome == 'success'
        run: |
          PLAN=$(cat plan.txt)
          echo "PLAN<<EOF" >> $GITHUB_ENV
          echo "$PLAN" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Apply Terraform
        if: steps.plan.outcome == 'success'
        id: apply
        continue-on-error: true
        run: |
          cd ${{ matrix.path }}
          terraform apply \
            -input=false \
            -no-color \
            tfplan

      - name: Post Plan and Apply to GitHub PR
        if: steps.plan.outcome == 'success' && steps.apply.outcome == 'success'
        uses: mshick/add-pr-comment@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'github-actions[bot]'
          message: |
            Applying **${{ matrix.path }}**:
            ```diff
            ${{ env.PLAN }}
            ```

            ```
            ${{ steps.apply.outputs.stdout }}
            ```
      - name: Post Plan Failure
        if: steps.plan.outcome == 'failure'
        uses: mshick/add-pr-comment@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'github-actions[bot]'
          message: |
            Plan failed for **${{ matrix.path }}**:
            ```
            ${{ steps.plan.outputs.stderr }}
            ```
      - name: Post Apply Failure
        if: steps.apply.outcome == 'failure'
        uses: mshick/add-pr-comment@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'github-actions[bot]'
          message: |
            Apply failed for **${{ matrix.path }}**:

            ```
            ${{ steps.apply.outputs.stderr }}
            ```


