name: "Terraform"

on:
  push:
    branches: [main]
  pull_request:
    types: [closed]

jobs:
  deployment:
    name: "Terraform"
    runs-on: ubuntu-latest
    environment:
      name: development
      url: https://github.com
    env:
      ADMIN_EMAIL: ${{ secrets.TF_API_TOKEN }}
      ORGANIZATION_NAME: ${{ secrets.ORGANIZATION_NAME }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          # terraform_version: 0.13.0:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'init'
